name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.13.x
            otp: 24
            warnings_as_errors: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
    
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v2
        id: mix_cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Mix Dependencies
        if: steps.mix_cache.outputs.cache-hit != 'true'
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.hex
            ~/.mix
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build
          
      - run: mix compile --warnings-as-errors
        if: matrix.warnings_as_errors
        
      - run: mix test
      
  mix_dialyzer:
    name: mix dialyzer (Elixir ${{matrix.elixir}} | OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.13.x
            otp: 24
            warnings_as_errors: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          elixir-version: 1.13.x
      
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v2
        id: mix_cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Install Mix Dependencies
        if: steps.mix_cache.outputs.cache-hit != 'true'
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.hex
            ~/.mix
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build
          
      - name: Restore PLT cache
        uses: actions/cache@v2
        id: plt_cache
        with:
          key: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-plt
          restore-keys: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-plt
          path: |
            priv/plts

      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt

      - name: Run dialyzer
        run: mix dialyzer
        
